### PR TITLE
htdp/universe: add mouse=?, make-color, bitmap/url

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

**Comment by stchang** [comment]
Do you remember why we didn't support `bitmap/url`? was it because of CORS blocking? I added it back because it seems to work (for some sites)

**Comment by stchang** [comment]
(see the archery example I'm adding to the playground)

**Comment by vishesh** [comment]
I think it was because we didn't do async/await and `bitmap-url` in Racket would be synchronous and JavaScript would be async. Speaking of which, we should probably think about async/await situation at some point.

**Review by vishesh — APPROVED** [review]

**Comment by vishesh** [comment]
Just to keep a note, referencing this to https://github.com/vishesh/racketscript/issues/84 for async/await.

**Comment by stchang** [comment]
Ah right. So it just might be slow? Is that causing this warning: `[Violation] 'load' handler took 157ms https://code.jquery.com/jquery-3.1.0.min.js`

**Comment by vishesh** [comment]
Not sure if that message is related. Its asynchronous, the I think what we'd observe is image now showing up on screen, or some kind of undefined values flying around (when accessing image attributed --- unless they initialized to 0). I've not checked that particular error yet.

**Pull request merged**
