### PR TITLE
add timeout-minutes to avoid endless tests on Racket 8.*

### PR DESCRIPTION
**Pull request by daynin**
- add timeout
- delete racket 6.9
- add racket 8.0

### CODE REVIEW

**Comment by stchang** [comment]
Did you mention that tests are passing with Racket 8.0 now? Should 8.0 be added to the matrix?

**Comment by stchang** [comment]
Actually some tests still fail for me using 8.0. I started a list here: https://github.com/vishesh/racketscript/issues/189

**Comment by daynin** [comment]
No, I didn't run tests on Racket 8.0. Added 8.0 version to the matrix

**Comment by stchang** [comment]
Do you know if there a way to "allow failures" in the gh actions config like you could with travis?

**Comment by daynin** [comment]
@stchang it can be a little bit tricky because GH Actions don't have the same feature, but I'll try to do that. You want to add an ability to skip fails of tests which run on 8.* version of Racket, right (just to be on the same page)?

**Comment by stchang** [comment]
Yes, allow failure of 8.0 and 8.1 right now, until we can fix it. Although it looks like the workflow gets marked as passing right now, even if some tests fail: https://github.com/vishesh/racketscript/issues/195

**Comment by daynin** [comment]
Ok, I'll try to do that

**Comment by daynin** [comment]
Now it has success status even if 8.* versions have failed tests or other errors https://github.com/vishesh/racketscript/actions/runs/853924052. But I don't know why here in PR it looks like failed

**Comment by vishesh** [comment]
Seems like 8.0 failures can be addressed separately, so I will just merge this.

**Pull request merged**
