### PR TITLE
interop fixes

### PR DESCRIPTION
**Pull request by stchang**

### CODE REVIEW

**Comment by stchang** [comment]
related to https://github.com/vishesh/racketscript-playground/issues/22

**Comment by vishesh** [comment]
Should we merge this? This is still marked as draft?

**Review by vishesh — APPROVED** [review]

**Comment by stchang** [comment]
I thought there would be more changes, as I was fixing the app. But it was just this one line. Can be merged now.

**Comment by vishesh** [comment]
Ok, both PRs can be merged then?

**Comment by stchang** [comment]
I need to fix the other one, bc `js-object?` behavior changed (https://github.com/vishesh/racketscript/pull/230/)

**Pull request merged**
