### PR TITLE
use non-deprecated KeyboardEvent methods

### LINKED ISSUE #20: on-key triggers on shift
In Racket, does `on-key` trigger when you press shift? I thought it didnt (will test later). Anyhow, RacketScript does and it makes it hard to enter capital letters.

### PR DESCRIPTION
**Pull request by stchang**
- fixes #20
- fixes Firefox hyphen issue

There may still be some issues but I tested it on all our example games.

### CODE REVIEW

**Comment by stchang** [comment]
I used the information here to determine deprecation: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

**Comment by vishesh** [comment]
Awesome! Regarding [Right/Left]Ctrl/Shift, the docs here[1] lists that there is ShiftLeft/ShiftRight/.... Anything I'm missing?

[1] https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code#Code_values

**Comment by stchang** [comment]
Yeah, I tried using `KeyboardEvent.code` first, but it was producing something like "KeyM" for basic keys, so I used `.key`, which required less translation. I guess I could special case the shift keys. I'll update the pr.

**Comment by stchang** [comment]
ok I handled left/right shifts and squashed the commits

**Pull request merged**
