### PR TITLE
fix: update eslint config to avoid rules we don't follow

### PR DESCRIPTION
**Pull request by daynin**
1. Add eslint into devDependencies.
2. Fix all autofixable issues.
3. Fix or ignore some other issues + add TODOs to fix them later.
4. Make some issues warnings because their fixing can lead to huge
refactoring.

### CODE REVIEW

**Comment by vishesh** [comment]
Hi @daynin ,

Thanks for fixing this. The patch overall looks good to me. Seems like our CI is out of credits (Travis is no longer free it seems), so didn't get the build results here. Did you by any chance run the tests using `make integration-tests`?

**Comment by daynin** [comment]
I tried to run tests on different version of Racket (6.12, 7.1, 8.0). For 6.12 we have the next results:

Optimizations: none
```
Failed tests (3/105) =>
  ✘ /Users/daynin/Documents/projects/racketscript/tests/experimental/keyword-args.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/sort.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/char.rkt

Skipped tests [4] =>
  □ /Users/daynin/Documents/projects/racketscript/tests/basic/__if-js.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift+1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift-1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift.rkt
  ```
  
  Optimizations: ALL
  ```
  Failed tests (3/111) =>
  ✘ /Users/daynin/Documents/projects/racketscript/tests/experimental/keyword-args.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/sort.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/char.rkt

Skipped tests [4] =>
  □ /Users/daynin/Documents/projects/racketscript/tests/basic/__if-js.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift+1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift-1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift.rkt
  0 tests/fixture.rkt
  ```
  
And one more thing for 6.12. Looks like tests in `tests/racket-core/hash.rkt` and `tests/racket-core/list.rkt` don't run at all, looks like there is an infinite loop or something like that. They just do nothing. The same thing happens for 7.1 and 8.0 but only with `tests/racket-core/hash.rkt`.
  
 

 For Racket 7.1 and 8.0:
  
  Optimizations: none
  ```
  Failed tests (10/106) =>
  ✘ /Users/daynin/Documents/projects/racketscript/tests/experimental/keyword-args.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/hash/mutation.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/threading.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/sort.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/list.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/closure-loop.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/closure-loop-2.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/char.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/racket-core/rx.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/racket-core/list.rkt

Skipped tests [4] =>
  □ /Users/daynin/Documents/projects/racketscript/tests/basic/__if-js.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift+1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift-1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift.rkt
  ```
  
  Optimizations: ALL
  ```
  Failed tests (11/112) =>
  ✘ /Users/daynin/Documents/projects/racketscript/tests/experimental/keyword-args.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/optimize/tail-map.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/hash/mutation.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/threading.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/sort.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/list.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/closure-loop.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/closure-loop-2.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/basic/char.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/racket-core/rx.rkt
  ✘ /Users/daynin/Documents/projects/racketscript/tests/racket-core/list.rkt

Skipped tests [4] =>
  □ /Users/daynin/Documents/projects/racketscript/tests/basic/__if-js.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift+1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift-1.rkt
  □ /Users/daynin/Documents/projects/racketscript/tests/modules/__import-shift.rkt
  0 tests/fixture.rkt
  ```
  
All results are the same for both branches `master` and `fix-eslint`. Maybe tests failings are somehow connected to my environment "MacOS 11.2".

But it seems that these changes do not affect tests.

**Comment by stchang** [comment]
The looping issue should have been fixed here https://github.com/vishesh/racketscript/issues/178 (and should have only affected Racket 7.6 or after, see https://github.com/racket/racket/issues/3471)

But it's of course possible we didnt properly fix it so thanks for the report! I will investigate.

**Comment by stchang** [comment]
Confirmed that the looping tests issue is back. 

Got all tests passing using commit 129b01de3522022ba523e058b96117e668377e79 (and Racket 7.8), so it must have been introduced in a commit after that.

**Comment by daynin** [comment]
The problem occurred here https://github.com/vishesh/racketscript/pull/183 (according to git bisect)

**Comment by vishesh** [comment]
Uh, I'm quite sure I ran all the tests for that PR and see the CI ran passing here: https://travis-ci.com/github/vishesh/racketscript/builds/216740787

**Comment by stchang** [comment]
I think @daynin might be saying that is the last passing commit? At least that is what I am seeing (using racket 7.8)

**Comment by daynin** [comment]
@vishesh yeah, you're right. It occurred after your PR. I ran tests in the PR's branch and they passed.

**Comment by vishesh** [comment]
I don't have any objection to merge this PR as master is broken anyway it seems, and PR unlikely would introduce any new regression.

**Comment by daynin** [comment]
@vishesh I almost completed fix for tests. Give me 5 minutes please, I'll send a PR

**Comment by daynin** [comment]
Fixed the problem here https://github.com/vishesh/racketscript/pull/188

**Comment by vishesh** [comment]
@daynin: Thank you for fixing this!!

**Pull request merged**
