### PR TITLE
Reformat JS: Replace tabs with spaces

### PR DESCRIPTION
**Pull request by glebm**
* Replaces tabs with spaces throughout.
* Add spaces around import braces as per most style guides (Google, AirBnb).
* Fix indentation for statements such as `switch` etc.
* Spaces around default parameters.

Now is good time as there are no outstanding PRs, nor JS runtime work-in-progress that I'm aware of.

Note that this is based on #108 which I assume will get merged by the time you get to this.
You can then rebase this PR with a single click.

GitHub doesn't show tabs vs spaces by default, but you can use this bookmarklet to review: https://gist.github.com/glebm/5b6c4517322193fbc51090dc3b57a44a

```
javascript:(function()%7Bfunction%20e(e%2Co%2Cr)%7Bconst%20c%3De.nodeValue.split(%22%5Ct%22).map(e%3D%3Ee.split(%22%20%22))%3Bif(1%3D%3D%3Dc.length%26%261%3D%3D%3Dc%5B0%5D.length)return%3Bconst%20a%3De.parentNode%2Cd%3Dt%3D%3E%7Ba.insertBefore(t%2Ce)%7D%3Bn(c%2Ce%3D%3E1%3D%3D%3De.length%26%26%22%22%3D%3D%3De%5B0%5D%2Ce%3D%3Ed(t(o.repeat(e)))%2Ce%3D%3En(e%2Ce%3D%3E%22%22%3D%3D%3De%2Ce%3D%3Ed(t(r.repeat(e)))%2Ce%3D%3Ed(document.createTextNode(e))))%2Ca.removeChild(e)%7Dfunction%20t(e)%7Bconst%20t%3Ddocument.createElement(%22span%22)%3Breturn%20t.textContent%3De%2Ct.style.opacity%3Dc%2Ct%7Dfunction%20n(e%2Ct%2Cn%2Co)%7Bconst%20r%3De.length%3Be.reduce((e%2Cc%2Ca)%3D%3E%7Bconst%20d%3Dt(c)%3Breturn%20d%26%26a!%3D%3Dr-1%3Fe%2B1%3A(e%3E0%26%26n(e)%2Cd%7C%7Co(c)%2C1)%7D%2C0)%7Dvar%20o%3D%22%C2%B7%22%2Cr%3D%22%E2%86%92%22%2Cc%3D.8%3B!function()%7Bfor(const%20t%20of%20document.querySelectorAll(%22table%5Bdata-tab-size%5D%22))%7Bconst%20n%3Dr.padEnd(%2Bt.dataset.tabSize)%2Cc%3Ddocument.createTreeWalker(t%2CNodeFilter.SHOW_TEXT%2C%7BacceptNode(e)%7Blet%20t%3De.parentNode%3Bfor(%3B%22TABLE%22!%3Dt.nodeName%3B)%7Bif(t.classList.contains(%22blob-code-inner%22))return%20t.firstChild!%3D%3De%7C%7C%22%20%22!%3D%3De.nodeValue%3FNodeFilter.FILTER_ACCEPT%3ANodeFilter.FILTER_SKIP%3Bt%3Dt.parentNode%7Dreturn%20NodeFilter.FILTER_SKIP%7D%7D)%2Ca%3D%5B%5D%3Bfor(%3Bc.nextNode()%3B)a.push(c.currentNode)%3Bfor(const%20t%20of%20a)e(t%2Cn%2Co)%7D%7D()%7D)()
```

### CODE REVIEW

**Comment by stchang** [comment]
Heh, nice. Were these changes generated with a tool?

**Comment by glebm** [comment]
@stchang I was going to run `clang-format`, but since it does full code reflow instead of just adjusting the whitespace, I've opted for vscode's auto-format functionality. As far as I can tell, vscode uses tsfmt, the TypeScript code formatter, which is very basic (no reflow, just indentation).

**Comment by vishesh** [comment]
Thanks for doing this!

**Comment by vishesh** [comment]
On side note, what style guide does this formatter use? Any ideas on how Google style guide compared to Airbnb? Recently I've mostly followed Airbnb, and IIRC Google guide was very Java'ish in style (I don't recall when I went through it).

**Comment by glebm** [comment]
@vishesh Not sure. However, both Google and JavaScript style guides use 2 spaces for indent, 4 spaces for continued indent. On one of my PRs, you asked me to use 4 spaces for indent. I'm not aware of any popular style guide that uses 4 spaces.

**Comment by vishesh** [comment]
@glebm Thanks for reminding me of that. I've to add exceptions on these guides. 4 spaces is the primary one that comes on top of my head.

Regarding Google vs Airbnb, IIRC I chose to follow Airbnb at that time because of better ES6 stuff. Regardless, both are good ones so its alright.

**Comment by glebm** [comment]
@vishesh Why not just switch to 2 spaces?

**Comment by vishesh** [comment]
Its an opinion with standard points on both sides, and there is no right answer. I don't think it is worth getting into this discussion.

**Comment by glebm** [comment]
So basically your answer is "I like 4 spaces". That's fine too, I just wanted to know why.

**Pull request merged**
